### ISSUE TITLE
Marshmallow 3.0.0rc6 support

### ISSUE THREAD

**Issue by alextremblay** [nonamenix/marshmallow-jam#3]
Hello,

First of all, thanks for making this, it looks really awesome!

Only problem i've encountered is that marshmallow 3.0.0rc6 dropped the `with_metaclass' function
```python
Python 3.7.2 (default, Mar 22 2019, 15:06:11)
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from jam import Schema
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alex/.pyenv/versions/vm-deploy/lib/python3.7/site-packages/jam/__init__.py", line 6, in <module>
    from marshmallow.schema import SchemaMeta as BaseSchemaMeta, BaseSchema, with_metaclass
ImportError: cannot import name 'with_metaclass' from 'marshmallow.schema' (/Users/alex/.pyenv/versions/vm-deploy/lib/python3.7/site-packages/marshmallow/schema.py)
```

**Comment by nonamenix** [comment]
fixed in https://github.com/nonamenix/marshmallow-jam/pull/6

**Comment by nonamenix** [comment]
deployed on https://pypi.org/project/marshmallow-jam/ with 1.2.0 version
